// src/components/EnvironmentSettings/EnvironmentSettingsPage.svelte
<script lang="ts">
  import { useGeolocationSettings } from '../../hooks/useGeolocationSettings.svelte';
  import { useProxySettings } from '../../hooks/useProxySettings.svelte';
  import type { ProxyProtocol } from '../../types/proxy-settings';
  import SettingsPageLayout from '../settings/SettingsPageLayout.svelte';
  import SettingsLoading from '../settings/SettingsLoading.svelte';
  import settingsStyles from '../../styles/settings-shared.module.css';
  import Button from '../ui/Button.svelte';
  import Input from '../ui/Input.svelte';
  import Select from '../ui/Select.svelte';
  import SegmentControl from '../ui/SegmentControl.svelte';
  import Alert from '../ui/Alert.svelte';
  import styles from './EnvironmentSettingsPage.module.css';
  type EnvTab = 'proxy' | 'geo';
  const ENV_TABS: { value: EnvTab; label: string }[] = [
    { value: 'proxy', label: '网络代理' },
    { value: 'geo', label: 'GPS 定位' },
  ];
  const PROXY_PROTOCOL_OPTIONS: { value: ProxyProtocol; label: string }[] = [
    { value: 'http', label: 'HTTP' },
    { value: 'https', label: 'HTTPS' },
    { value: 'socks5', label: 'SOCKS5' },
  ];
  function parseCoordinate(value: string, fallback: number): number {
    const parsed = Number.parseFloat(value);
    return Number.isFinite(parsed) ? parsed : fallback;
  }
  let activeTab: EnvTab = $state.raw('proxy');
  function setActiveTab(
    value: typeof activeTab | ((prev: typeof activeTab) => typeof activeTab),
  ) {
    activeTab = typeof value === 'function' ? value(activeTab) : value;
  }
  const proxy = useProxySettings();
  const geo = useGeolocationSettings();
  let proxyProfileList = $derived.by(() =>
    Object.values(proxy.settings.profiles),
  );
  let geoProfileList = $derived.by(() => Object.values(geo.settings.profiles));
  let isLoading = $derived(proxy.isLoading || geo.isLoading);
  let isSaving = $derived(proxy.isSaving || geo.isSaving);
  let error = $derived(proxy.error || geo.error);
  let saveMessage = $derived(
    [proxy.saveMessage, geo.saveMessage].filter(Boolean).join(' '),
  );
</script>

{#if isLoading}<SettingsLoading message="加载环境设置..."
  ></SettingsLoading>{:else}<SettingsPageLayout
    title="网络与定位"
    description="定义代理与 GPS 预设，在「网站管理」中为各站分配。"
    ariaLabel="网络与定位设置"
    class={styles.pageCompact}
  >
    {#snippet footer()}<div class={styles.footerCompact}>
        {#if error}<Alert variant="error">
            {error}
          </Alert>{/if}{#if saveMessage}<Alert variant="success">
            {saveMessage}
          </Alert>{/if}
        <div class={styles.footerActions}>
          <Button
            size="sm"
            onclick={() => {
              void proxy.saveSettings();
              void geo.saveSettings();
            }}
            disabled={isSaving}
          >
            {isSaving ? '保存中...' : '立即应用'}
          </Button><Button
            size="sm"
            variant="outline"
            onclick={() => {
              void proxy.loadSettings();
              void geo.loadSettings();
            }}
            disabled={isSaving}
          >
            重新加载
          </Button>
        </div>
      </div>{/snippet}
    <div class={styles.toolbar}>
      <SegmentControl
        options={ENV_TABS}
        value={activeTab}
        onChange={setActiveTab}
        ariaLabel="环境设置分类"
      ></SegmentControl>{#if activeTab === 'proxy'}<Button
          size="sm"
          variant="outline"
          onclick={proxy.addProfile}
          disabled={isSaving}
        >
          添加代理
        </Button>{:else}<Button
          size="sm"
          variant="outline"
          onclick={geo.addProfile}
          disabled={isSaving}
        >
          添加位置
        </Button>{/if}
    </div>
    {#if activeTab === 'proxy'}<section
        class={styles.section}
        aria-label="代理库"
      >
        {#if proxyProfileList.length === 0}<p class={styles.emptyHint}>
            暂无代理，点击「添加代理」创建。
          </p>{:else}<div class={styles.profileList}>
            {#each proxyProfileList as profile (profile.id)}<article
                class={styles.profileCard}
                aria-label={`代理 ${profile.name}`}
              >
                <div class={styles.profileCardHeader}>
                  <Input
                    label="名称"
                    placeholder="本地 Clash"
                    value={profile.name}
                    oninput={(event) =>
                      proxy.updateProfile(profile.id, {
                        name: event.currentTarget.value,
                      })}
                  ></Input><Button
                    size="sm"
                    variant="outline"
                    onclick={() => proxy.removeProfile(profile.id)}
                    disabled={isSaving}
                  >
                    删除
                  </Button>
                </div>
                <div class={styles.proxyFields}>
                  <div class={settingsStyles.fieldGroup}>
                    <label
                      class={settingsStyles.label}
                      for={`${profile.id}-protocol`}
                    >
                      协议
                    </label>
                    <Select
                      id={`${profile.id}-protocol`}
                      value={profile.protocol || 'http'}
                      onchange={(event) =>
                        proxy.updateProfile(profile.id, {
                          protocol: event.currentTarget.value as ProxyProtocol,
                        })}
                    >
                      {#each PROXY_PROTOCOL_OPTIONS as option (option.value)}<option
                          value={option.value}
                        >
                          {option.label}
                        </option>{/each}
                    </Select>
                  </div>
                  <Input
                    label="主机"
                    placeholder="127.0.0.1"
                    value={profile.host || ''}
                    oninput={(event) =>
                      proxy.updateProfile(profile.id, {
                        host: event.currentTarget.value,
                      })}
                  ></Input><Input
                    label="端口"
                    placeholder="7890"
                    value={profile.port || ''}
                    oninput={(event) =>
                      proxy.updateProfile(profile.id, {
                        port: event.currentTarget.value,
                      })}
                  ></Input>
                </div>
                <div class={styles.proxyAuthFields}>
                  <Input
                    label="用户名"
                    placeholder="可选"
                    value={profile.username || ''}
                    oninput={(event) =>
                      proxy.updateProfile(profile.id, {
                        username: event.currentTarget.value,
                      })}
                    autocomplete="off"
                  ></Input><Input
                    label="密码"
                    type="password"
                    placeholder="可选"
                    value={profile.password || ''}
                    oninput={(event) =>
                      proxy.updateProfile(profile.id, {
                        password: event.currentTarget.value,
                      })}
                    autocomplete="off"
                  ></Input>
                </div>
              </article>{/each}
          </div>{/if}
      </section>{:else}<section class={styles.section} aria-label="位置库">
        {#if geoProfileList.length === 0}<p class={styles.emptyHint}>
            暂无位置，点击「添加位置」创建。
          </p>{:else}<div class={styles.profileList}>
            {#each geoProfileList as profile (profile.id)}<article
                class={styles.profileCard}
                aria-label={`位置 ${profile.name}`}
              >
                <div class={styles.profileCardHeader}>
                  <Input
                    label="名称"
                    placeholder="北京"
                    value={profile.name}
                    oninput={(event) =>
                      geo.updateProfile(profile.id, {
                        name: event.currentTarget.value,
                      })}
                  ></Input><Button
                    size="sm"
                    variant="outline"
                    onclick={() => geo.removeProfile(profile.id)}
                    disabled={isSaving}
                  >
                    删除
                  </Button>
                </div>
                <div class={styles.coordFields}>
                  <Input
                    label="纬度"
                    placeholder="39.9042"
                    value={String(profile.latitude)}
                    oninput={(event) =>
                      geo.updateProfile(profile.id, {
                        latitude: parseCoordinate(
                          event.currentTarget.value,
                          profile.latitude,
                        ),
                      })}
                  ></Input><Input
                    label="经度"
                    placeholder="116.4074"
                    value={String(profile.longitude)}
                    oninput={(event) =>
                      geo.updateProfile(profile.id, {
                        longitude: parseCoordinate(
                          event.currentTarget.value,
                          profile.longitude,
                        ),
                      })}
                  ></Input><Input
                    label="精度(m)"
                    placeholder="100"
                    value={String(profile.accuracy)}
                    oninput={(event) =>
                      geo.updateProfile(profile.id, {
                        accuracy: parseCoordinate(
                          event.currentTarget.value,
                          profile.accuracy,
                        ),
                      })}
                  ></Input>
                </div>
              </article>{/each}
          </div>{/if}
      </section>{/if}
  </SettingsPageLayout>{/if}

// src/components/EnvironmentSettings/EnvironmentSettingsPage.tsx
import { useMemo, useState } from 'react';
import { useGeolocationSettings } from '../../hooks/useGeolocationSettings';
import { useProxySettings } from '../../hooks/useProxySettings';
import type { ProxyProtocol } from '../../types/proxy-settings';
import SettingsPageLayout, { SettingsLoading, settingsStyles } from '../settings/SettingsPageLayout';
import { Button } from '../ui/Button';
import { Input } from '../ui/Input';
import { Select } from '../ui/Select';
import { SegmentControl } from '../ui/SegmentControl';
import { Alert } from '../ui/Alert';
import styles from './EnvironmentSettingsPage.module.css';

type EnvTab = 'proxy' | 'geo';

const ENV_TABS: { value: EnvTab; label: string }[] = [
  { value: 'proxy', label: '网络代理' },
  { value: 'geo', label: 'GPS 定位' },
];

const PROXY_PROTOCOL_OPTIONS: { value: ProxyProtocol; label: string }[] = [
  { value: 'http', label: 'HTTP' },
  { value: 'https', label: 'HTTPS' },
  { value: 'socks5', label: 'SOCKS5' },
];

function parseCoordinate(value: string, fallback: number): number {
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

const EnvironmentSettingsPage: React.FC = () => {
  const [activeTab, setActiveTab] = useState<EnvTab>('proxy');
  const proxy = useProxySettings();
  const geo = useGeolocationSettings();

  const proxyProfileList = useMemo(
    () => Object.values(proxy.settings.profiles),
    [proxy.settings.profiles]
  );

  const geoProfileList = useMemo(
    () => Object.values(geo.settings.profiles),
    [geo.settings.profiles]
  );

  const isLoading = proxy.isLoading || geo.isLoading;
  const isSaving = proxy.isSaving || geo.isSaving;
  const error = proxy.error || geo.error;
  const saveMessage = [proxy.saveMessage, geo.saveMessage].filter(Boolean).join(' ');

  if (isLoading) {
    return <SettingsLoading message="加载环境设置..." />;
  }

  return (
    <SettingsPageLayout
      title="网络与定位"
      description="定义代理与 GPS 预设，在「网站管理」中为各站分配。"
      ariaLabel="网络与定位设置"
      className={styles.pageCompact}
      footer={
        <div className={styles.footerCompact}>
          {error && <Alert variant="error">{error}</Alert>}
          {saveMessage && <Alert variant="success">{saveMessage}</Alert>}
          <div className={styles.footerActions}>
            <Button
              size="sm"
              onClick={() => {
                void proxy.saveSettings();
                void geo.saveSettings();
              }}
              disabled={isSaving}
            >
              {isSaving ? '保存中...' : '立即应用'}
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={() => {
                void proxy.loadSettings();
                void geo.loadSettings();
              }}
              disabled={isSaving}
            >
              重新加载
            </Button>
          </div>
        </div>
      }
    >
      <div className={styles.toolbar}>
        <SegmentControl
          options={ENV_TABS}
          value={activeTab}
          onChange={setActiveTab}
          ariaLabel="环境设置分类"
        />
        {activeTab === 'proxy' ? (
          <Button size="sm" variant="outline" onClick={proxy.addProfile} disabled={isSaving}>
            添加代理
          </Button>
        ) : (
          <Button size="sm" variant="outline" onClick={geo.addProfile} disabled={isSaving}>
            添加位置
          </Button>
        )}
      </div>

      {activeTab === 'proxy' ? (
        <section className={styles.section} aria-label="代理库">
          {proxyProfileList.length === 0 ? (
            <p className={styles.emptyHint}>暂无代理，点击「添加代理」创建。</p>
          ) : (
            <div className={styles.profileList}>
              {proxyProfileList.map((profile) => (
                <article key={profile.id} className={styles.profileCard} aria-label={`代理 ${profile.name}`}>
                  <div className={styles.profileCardHeader}>
                    <Input
                      label="名称"
                      placeholder="本地 Clash"
                      value={profile.name}
                      onChange={(event) =>
                        proxy.updateProfile(profile.id, { name: event.target.value })
                      }
                    />
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => proxy.removeProfile(profile.id)}
                      disabled={isSaving}
                    >
                      删除
                    </Button>
                  </div>

                  <div className={styles.proxyFields}>
                    <div className={settingsStyles.fieldGroup}>
                      <label className={settingsStyles.label} htmlFor={`${profile.id}-protocol`}>
                        协议
                      </label>
                      <Select
                        id={`${profile.id}-protocol`}
                        value={profile.protocol || 'http'}
                        onChange={(event) =>
                          proxy.updateProfile(profile.id, {
                            protocol: event.target.value as ProxyProtocol,
                          })
                        }
                      >
                        {PROXY_PROTOCOL_OPTIONS.map((option) => (
                          <option key={option.value} value={option.value}>
                            {option.label}
                          </option>
                        ))}
                      </Select>
                    </div>
                    <Input
                      label="主机"
                      placeholder="127.0.0.1"
                      value={profile.host || ''}
                      onChange={(event) =>
                        proxy.updateProfile(profile.id, { host: event.target.value })
                      }
                    />
                    <Input
                      label="端口"
                      placeholder="7890"
                      value={profile.port || ''}
                      onChange={(event) =>
                        proxy.updateProfile(profile.id, { port: event.target.value })
                      }
                    />
                  </div>

                  <div className={styles.proxyAuthFields}>
                    <Input
                      label="用户名"
                      placeholder="可选"
                      value={profile.username || ''}
                      onChange={(event) =>
                        proxy.updateProfile(profile.id, { username: event.target.value })
                      }
                      autoComplete="off"
                    />
                    <Input
                      label="密码"
                      type="password"
                      placeholder="可选"
                      value={profile.password || ''}
                      onChange={(event) =>
                        proxy.updateProfile(profile.id, { password: event.target.value })
                      }
                      autoComplete="off"
                    />
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      ) : (
        <section className={styles.section} aria-label="位置库">
          {geoProfileList.length === 0 ? (
            <p className={styles.emptyHint}>暂无位置，点击「添加位置」创建。</p>
          ) : (
            <div className={styles.profileList}>
              {geoProfileList.map((profile) => (
                <article key={profile.id} className={styles.profileCard} aria-label={`位置 ${profile.name}`}>
                  <div className={styles.profileCardHeader}>
                    <Input
                      label="名称"
                      placeholder="北京"
                      value={profile.name}
                      onChange={(event) =>
                        geo.updateProfile(profile.id, { name: event.target.value })
                      }
                    />
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => geo.removeProfile(profile.id)}
                      disabled={isSaving}
                    >
                      删除
                    </Button>
                  </div>

                  <div className={styles.coordFields}>
                    <Input
                      label="纬度"
                      placeholder="39.9042"
                      value={String(profile.latitude)}
                      onChange={(event) =>
                        geo.updateProfile(profile.id, {
                          latitude: parseCoordinate(event.target.value, profile.latitude),
                        })
                      }
                    />
                    <Input
                      label="经度"
                      placeholder="116.4074"
                      value={String(profile.longitude)}
                      onChange={(event) =>
                        geo.updateProfile(profile.id, {
                          longitude: parseCoordinate(event.target.value, profile.longitude),
                        })
                      }
                    />
                    <Input
                      label="精度(m)"
                      placeholder="100"
                      value={String(profile.accuracy)}
                      onChange={(event) =>
                        geo.updateProfile(profile.id, {
                          accuracy: parseCoordinate(event.target.value, profile.accuracy),
                        })
                      }
                    />
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>
      )}
    </SettingsPageLayout>
  );
};

export default EnvironmentSettingsPage;
