// src/components/MultiWebviewGrid.tsx
import { memo, useMemo, useRef, useCallback, useState, useEffect } from 'react';
import { AITool } from '../types/ai-tool';
import { InputDeliveryState } from '../types/input-delivery';
import { getSiteHandler } from '../webview-handlers';
import { preInjectScript } from './WebviewInputHandler';
import { ElectronWebView, type ElectronWebViewElement } from './ElectronWebView';
import { getToolPartition } from '../utils/toolPartition';
import { getFaviconFallbackUrl, getLoadableFaviconUrl } from '../utils/favicon';
import Icon from './ui/Icon';
import styles from './MultiWebviewGrid.module.css';

type PageFaviconUpdatedEvent = Event & { favicons?: string[] };

type WebviewElement = ElectronWebViewElement;

interface MultiWebviewGridProps {
  tools: AITool[];
  selectedToolIds: string[];
  deliveryStates: Record<string, InputDeliveryState>;
  proxyRevision?: number;
  onRetry?: (toolId: string) => void;
  onWebviewRef?: (toolId: string, element: HTMLElement | null) => void;
}

function renderTabStatus(status: InputDeliveryState['status'] | 'pending') {
  if (status === 'sending') {
    return (
      <span className={styles.tabStatus} aria-label="发送中">
        ⏳
      </span>
    );
  }
  if (status === 'success') {
    return (
      <span className={styles.tabStatus} aria-label="发送成功">
        ✓
      </span>
    );
  }
  if (status === 'error') {
    return (
      <span className={styles.tabStatus} aria-label="发送失败">
        ✗
      </span>
    );
  }
  return null;
}

const MultiWebviewGrid: React.FC<MultiWebviewGridProps> = memo(({
  tools,
  selectedToolIds,
  deliveryStates,
  proxyRevision = 0,
  onRetry,
  onWebviewRef,
}) => {
  const webviewRefs = useRef<Record<string, WebviewElement>>({});
  const webviewReadyRef = useRef<Record<string, boolean>>({});
  const listenerCleanups = useRef<Record<string, () => void>>({});
  const activeTabIdRef = useRef('');
  const [activeTabId, setActiveTabId] = useState<string>('');
  const [favicons, setFavicons] = useState<Record<string, string>>({});
  const [canGoBack, setCanGoBack] = useState(false);
  const [canGoForward, setCanGoForward] = useState(false);
  const [isClearingData, setIsClearingData] = useState(false);

  const syncNavState = useCallback((toolId: string) => {
    const webview = webviewRefs.current[toolId];
    if (!webview || !webviewReadyRef.current[toolId]) {
      setCanGoBack(false);
      setCanGoForward(false);
      return;
    }
    try {
      setCanGoBack(Boolean(webview.canGoBack?.()));
      setCanGoForward(Boolean(webview.canGoForward?.()));
    } catch {
      setCanGoBack(false);
      setCanGoForward(false);
    }
  }, []);

  const selectedTools = useMemo(() => {
    return tools.filter((tool) => selectedToolIds.includes(tool.id));
  }, [tools, selectedToolIds]);

  const activeTool = useMemo(
    () => selectedTools.find((tool) => tool.id === activeTabId) ?? selectedTools[0],
    [selectedTools, activeTabId]
  );

  useEffect(() => {
    if (!selectedToolIds.length) {
      setActiveTabId('');
      return;
    }
    if (!activeTabId || !selectedToolIds.includes(activeTabId)) {
      setActiveTabId(selectedToolIds[0]);
    }
  }, [selectedToolIds, activeTabId]);

  useEffect(() => {
    activeTabIdRef.current = activeTabId;
    if (activeTabId) {
      syncNavState(activeTabId);
    }
  }, [activeTabId, syncNavState]);

  const handleWebviewRef = useCallback((toolId: string, toolName: string, element: HTMLElement | null) => {
    listenerCleanups.current[toolId]?.();
    delete listenerCleanups.current[toolId];

    if (element) {
      const webview = element as WebviewElement;
      webviewRefs.current[toolId] = webview;
      webviewReadyRef.current[toolId] = false;
      onWebviewRef?.(toolId, element);

      const onDomReady = () => {
        webviewReadyRef.current[toolId] = true;
        if (toolId === activeTabIdRef.current) {
          syncNavState(toolId);
        }
      };

      const onLoad = async () => {
        syncNavState(toolId);

        const el = webviewRefs.current[toolId];
        if (el && getSiteHandler(toolId)) {
          try {
            await preInjectScript(
              el as HTMLElement & { executeJavaScript?: (code: string) => Promise<unknown> },
              toolId,
              5000
            );
          } catch (error) {
            console.error(`[MultiWebviewGrid] ${toolName} 预注入脚本失败:`, error);
          }
        }

        try {
          await window.electronAPI?.applyToolGeolocation(toolId);
        } catch (error) {
          console.warn(`[MultiWebviewGrid] ${toolName} 应用 GPS 设置失败:`, error);
        }
      };

      const onFaviconUpdated = (event: Event) => {
        const faviconUrl = (event as PageFaviconUpdatedEvent).favicons?.[0];
        const loadableUrl = faviconUrl ? getLoadableFaviconUrl(faviconUrl) : '';
        if (loadableUrl) {
          setFavicons((prev) => ({ ...prev, [toolId]: loadableUrl }));
        }
      };

      const onNavigate = () => {
        if (toolId === activeTabIdRef.current) {
          syncNavState(toolId);
        }
      };

      webview.addEventListener?.('dom-ready', onDomReady);
      webview.addEventListener?.('did-finish-load', onLoad);
      webview.addEventListener?.('did-navigate', onNavigate);
      webview.addEventListener?.('did-navigate-in-page', onNavigate);
      webview.addEventListener?.('page-favicon-updated', onFaviconUpdated);
      listenerCleanups.current[toolId] = () => {
        webview.removeEventListener?.('dom-ready', onDomReady);
        webview.removeEventListener?.('did-finish-load', onLoad);
        webview.removeEventListener?.('did-navigate', onNavigate);
        webview.removeEventListener?.('did-navigate-in-page', onNavigate);
        webview.removeEventListener?.('page-favicon-updated', onFaviconUpdated);
      };
    } else {
      delete webviewRefs.current[toolId];
      delete webviewReadyRef.current[toolId];
      onWebviewRef?.(toolId, null);
    }
  }, [onWebviewRef, syncNavState]);

  const handleRefresh = useCallback((toolId: string, url: string) => {
    const webview = webviewRefs.current[toolId];
    if (!webview) {
      return;
    }

    if (typeof webview.reload === 'function') {
      webview.reload();
      return;
    }

    webview.src = '';
    setTimeout(() => {
      webview.src = url;
    }, 100);
  }, []);

  const handleGoBack = useCallback((toolId: string) => {
    const webview = webviewRefs.current[toolId];
    if (!webview || !webviewReadyRef.current[toolId]) {
      return;
    }
    try {
      webview.goBack?.();
      syncNavState(toolId);
    } catch {
      // webview 尚未就绪
    }
  }, [syncNavState]);

  const handleGoForward = useCallback((toolId: string) => {
    const webview = webviewRefs.current[toolId];
    if (!webview || !webviewReadyRef.current[toolId]) {
      return;
    }
    try {
      webview.goForward?.();
      syncNavState(toolId);
    } catch {
      // webview 尚未就绪
    }
  }, [syncNavState]);

  const handleClearCache = useCallback(
    async (toolId: string, toolName: string, url: string) => {
      const confirmed = window.confirm(
        `确定清理「${toolName}」的所有缓存数据吗？\n\n将清除 Cookie、本地存储与网络缓存，可能需要重新登录。`
      );
      if (!confirmed) {
        return;
      }

      if (!window.electronAPI?.clearToolWebviewData) {
        window.alert('当前环境不支持清理缓存');
        return;
      }

      setIsClearingData(true);
      try {
        const result = await window.electronAPI.clearToolWebviewData(toolId);
        if (!result.success) {
          window.alert(result.error ?? '清理缓存失败');
          return;
        }

        const webview = webviewRefs.current[toolId];
        if (webview) {
          webview.src = url;
        }
        syncNavState(toolId);
      } catch (error) {
        window.alert(error instanceof Error ? error.message : '清理缓存失败');
      } finally {
        setIsClearingData(false);
      }
    },
    [syncNavState]
  );

  if (!selectedTools.length) {
    return (
      <div className={styles.emptyState}>
        <p>请至少选择一个 AI 工具</p>
      </div>
    );
  }

  return (
    <div className={styles.tabsRoot}>
      <div className={styles.tabBar} role="tablist" aria-label="AI 工具标签页">
        {selectedTools.map((tool) => {
          const deliveryState = deliveryStates[tool.id];
          const status = deliveryState?.status || 'pending';
          const isActive = tool.id === activeTabId;
          const faviconUrl =
            favicons[tool.id] || tool.icon || getFaviconFallbackUrl(tool.url);

          return (
            <button
              key={tool.id}
              type="button"
              role="tab"
              id={`tab-${tool.id}`}
              aria-selected={isActive}
              aria-controls={`panel-${tool.id}`}
              className={`${styles.tab} ${isActive ? styles.tabActive : ''}`}
              onClick={() => setActiveTabId(tool.id)}
            >
              {faviconUrl && (
                <img
                  src={faviconUrl}
                  alt=""
                  className={styles.tabIcon}
                  aria-hidden="true"
                />
              )}
              <span className={styles.tabLabel}>{tool.name}</span>
              {renderTabStatus(status)}
            </button>
          );
        })}

        {activeTool && (
          <div className={styles.tabBarActions}>
            {deliveryStates[activeTool.id]?.status === 'error' && onRetry && (
              <button
                type="button"
                className={styles.retryButton}
                onClick={() => onRetry(activeTool.id)}
                aria-label={`重试 ${activeTool.name}`}
              >
                重试
              </button>
            )}
            <button
              type="button"
              className={styles.toolbarButton}
              onClick={() => handleGoBack(activeTool.id)}
              disabled={!canGoBack}
              aria-label={`后退 ${activeTool.name}`}
              title="后退"
            >
              <Icon name="ArrowLeft" size={16} />
            </button>
            <button
              type="button"
              className={styles.toolbarButton}
              onClick={() => handleGoForward(activeTool.id)}
              disabled={!canGoForward}
              aria-label={`前进 ${activeTool.name}`}
              title="前进"
            >
              <Icon name="ArrowRight" size={16} />
            </button>
            <button
              type="button"
              className={styles.toolbarButton}
              onClick={() => handleRefresh(activeTool.id, activeTool.url)}
              aria-label={`刷新 ${activeTool.name}`}
              title="刷新当前页面"
            >
              <Icon name="RefreshCw" size={16} />
            </button>
            <button
              type="button"
              className={`${styles.toolbarButton} ${styles.toolbarButtonDanger}`}
              onClick={() => handleClearCache(activeTool.id, activeTool.name, activeTool.url)}
              disabled={isClearingData}
              aria-label={`清理 ${activeTool.name} 缓存`}
              title="清理所有缓存数据"
            >
              <Icon name="Eraser" size={16} />
            </button>
          </div>
        )}
      </div>

      <div className={styles.tabPanels}>
        {selectedTools.map((tool) => {
          const deliveryState = deliveryStates[tool.id];
          const isActive = tool.id === activeTabId;

          return (
            <div
              key={tool.id}
              id={`panel-${tool.id}`}
              role="tabpanel"
              aria-labelledby={`tab-${tool.id}`}
              className={`${styles.tabPane} ${isActive ? styles.tabPaneActive : styles.tabPaneHidden}`}
              aria-hidden={!isActive}
            >
              <div className={styles.webviewContainer} aria-label={`${tool.name} 内容区域`}>
                <ElectronWebView
                  key={`${tool.id}-${proxyRevision}`}
                  ref={(el) => handleWebviewRef(tool.id, tool.name, el)}
                  partition={getToolPartition(tool.id)}
                  data-tool-id={tool.id}
                  src={tool.url}
                  style={{
                    width: '100%',
                    height: '100%',
                    display: 'inline-flex',
                  }}
                  webpreferences="allowRunningInsecureContent=true, javascript=yes"
                  aria-label={`${tool.name} Webview`}
                />
              </div>
              {isActive && deliveryState?.status === 'error' && deliveryState.errorMessage && (
                <div className={styles.errorMessage} role="alert">
                  {deliveryState.errorMessage}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
});

MultiWebviewGrid.displayName = 'MultiWebviewGrid';

export default MultiWebviewGrid;

// src/components/MultiWebviewGrid.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import type { AITool } from '../types/ai-tool';
  import type { InputDeliveryState } from '../types/input-delivery';
  import { getSiteHandler } from '../webview-handlers';
  import { preInjectScript } from './WebviewInputHandler';
  import ElectronWebView, {
    type ElectronWebViewElement,
  } from './ElectronWebView.svelte';
  import { getToolPartitionFromSettings } from '../utils/toolPartition';
  import { getSessionSettingsSnapshot } from '../hooks/useSessionSettings.svelte';
  import { isToolIncognito } from '../types/session-settings';
  import {
    getFaviconFallbackUrl,
    getLoadableFaviconUrl,
  } from '../utils/favicon';
  import Icon from './ui/Icon.svelte';
  import styles from './MultiWebviewGrid.module.css';

  let {
    tools,
    selectedToolIds,
    deliveryStates,
    proxyRevision = 0,
    sessionRevision = 0,
    onRetry,
    onWebviewRef,
  }: {
    tools: AITool[];
    selectedToolIds: string[];
    deliveryStates: Record<string, InputDeliveryState>;
    proxyRevision?: number;
    sessionRevision?: number;
    onRetry?: (id: string) => void;
    onWebviewRef?: (id: string, element: HTMLElement | null) => void;
  } = $props();
  const webviews: Record<string, ElectronWebViewElement> = {};
  const ready: Record<string, boolean> = {};
  const cleanups: Record<string, () => void> = {};
  let activeTabId = $state('');
  let favicons = $state.raw<Record<string, string>>({});
  let canGoBack = $state(false);
  let canGoForward = $state(false);
  let isClearingData = $state(false);
  const selectedTools = $derived(
    tools.filter((tool) => selectedToolIds.includes(tool.id)),
  );
  const activeTool = $derived(
    selectedTools.find((tool) => tool.id === activeTabId) ?? selectedTools[0],
  );
  const session = $derived.by(() => {
    void sessionRevision;
    return getSessionSettingsSnapshot();
  });

  $effect(() => {
    if (!selectedTools.some((tool) => tool.id === activeTabId))
      activeTabId = selectedTools[0]?.id ?? '';
  });
  $effect(() => {
    const id = activeTabId;
    untrack(() => syncNavState(id));
  });

  function syncNavState(id: string) {
    if (id !== activeTabId) return;
    const view = webviews[id];
    try {
      canGoBack = !!(ready[id] && view?.canGoBack?.());
      canGoForward = !!(ready[id] && view?.canGoForward?.());
    } catch {
      canGoBack = canGoForward = false;
    }
  }

  function attach(
    tool: AITool,
    incognito: boolean,
    view: ElectronWebViewElement,
  ) {
    cleanups[tool.id]?.();
    delete cleanups[tool.id];
    webviews[tool.id] = view;
    ready[tool.id] = false;
    onWebviewRef?.(tool.id, view);
    let disposed = false;
    const onReady = () => {
      ready[tool.id] = true;
      syncNavState(tool.id);
    };
    const onNavigate = () => syncNavState(tool.id);
    const onLoad = async () => {
      syncNavState(tool.id);
      if (getSiteHandler(tool.id)) {
        try {
          await preInjectScript(view, tool.id, 5000);
        } catch (error) {
          console.error(`[${tool.name}] 预注入脚本失败:`, error);
        }
      }
      if (disposed) return;
      try {
        await window.electronAPI?.applyToolGeolocation(tool.id);
      } catch (error) {
        console.warn(`[${tool.name}] 应用 GPS 设置失败:`, error);
      }
    };
    const onFavicon = (event: Event) => {
      const url = (event as Event & { favicons?: string[] }).favicons?.[0];
      const loadable = url ? getLoadableFaviconUrl(url) : '';
      if (loadable) favicons = { ...favicons, [tool.id]: loadable };
    };
    const listeners: [string, EventListener][] = [
      ['dom-ready', onReady],
      ['did-finish-load', onLoad],
      ['did-navigate', onNavigate],
      ['did-navigate-in-page', onNavigate],
      ['page-favicon-updated', onFavicon],
    ];
    for (const [name, listener] of listeners)
      view.addEventListener(name, listener);
    cleanups[tool.id] = () => {
      if (disposed) return;
      disposed = true;
      for (const [name, listener] of listeners)
        view.removeEventListener(name, listener);
      if (webviews[tool.id] === view) {
        delete webviews[tool.id];
        delete ready[tool.id];
        onWebviewRef?.(tool.id, null);
      }
      if (incognito)
        void window.electronAPI?.clearIncognitoPartition?.(tool.id);
    };
    return cleanups[tool.id];
  }

  function navigate(direction: 'goBack' | 'goForward') {
    if (!activeTool || !ready[activeTool.id]) return;
    try {
      webviews[activeTool.id]?.[direction]?.();
      syncNavState(activeTool.id);
    } catch {
      /* The guest may have navigated away while handling the click. */
    }
  }
  function refresh() {
    if (!activeTool) return;
    const view = webviews[activeTool.id];
    if (view?.reload) view.reload();
    else if (view) view.src = activeTool.url;
  }
  async function clearCache() {
    const tool = activeTool;
    if (
      !tool ||
      !window.confirm(
        `确定清理「${tool.name}」的所有缓存数据吗？\n\n将清除 Cookie、本地存储与网络缓存，可能需要重新登录。`,
      )
    )
      return;
    if (!window.electronAPI?.clearToolWebviewData) {
      window.alert('当前环境不支持清理缓存');
      return;
    }
    isClearingData = true;
    try {
      const result = await window.electronAPI.clearToolWebviewData(tool.id);
      if (!result.success) {
        window.alert(result.error ?? '清理缓存失败');
        return;
      }
      if (webviews[tool.id]) webviews[tool.id].src = tool.url;
      syncNavState(tool.id);
    } catch (error) {
      window.alert(error instanceof Error ? error.message : '清理缓存失败');
    } finally {
      isClearingData = false;
    }
  }
  function moveTab(event: KeyboardEvent, index: number) {
    const next =
      event.key === 'ArrowRight'
        ? (index + 1) % selectedTools.length
        : event.key === 'ArrowLeft'
          ? (index - 1 + selectedTools.length) % selectedTools.length
          : event.key === 'Home'
            ? 0
            : event.key === 'End'
              ? selectedTools.length - 1
              : -1;
    if (next < 0) return;
    event.preventDefault();
    activeTabId = selectedTools[next].id;
    document.getElementById(`tab-${activeTabId}`)?.focus();
  }
</script>

{#if !selectedTools.length}
  <div class={styles.emptyState}><p>请至少选择一个 AI 工具</p></div>
{:else}
  <div class={styles.tabsRoot}>
    <div class={styles.tabBar} role="tablist" aria-label="AI 工具标签页">
      {#each selectedTools as tool, index (tool.id)}
        {@const status = deliveryStates[tool.id]?.status}
        {@const incognito = isToolIncognito(session, tool.id)}
        {@const favicon =
          favicons[tool.id] || tool.icon || getFaviconFallbackUrl(tool.url)}
        <button
          type="button"
          role="tab"
          id={`tab-${tool.id}`}
          aria-selected={tool.id === activeTabId}
          aria-controls={`panel-${tool.id}`}
          tabindex={tool.id === activeTabId ? 0 : -1}
          class={`${styles.tab} ${tool.id === activeTabId ? styles.tabActive : ''} ${incognito ? styles.tabIncognito : ''}`}
          onclick={() => (activeTabId = tool.id)}
          onkeydown={(event) => moveTab(event, index)}
        >
          {#if incognito}<span
              class={styles.tabIncognitoBadge}
              title="无痕模式"
            >
              <Icon name="EyeOff" size={12} />
            </span>{/if}
          {#if favicon}<img
              src={favicon}
              alt=""
              class={styles.tabIcon}
              aria-hidden="true"
            />{/if}
          <span class={styles.tabLabel}>{tool.name}</span>
          {#if status && status !== 'pending'}
            <span
              class={styles.tabStatus}
              aria-label={status === 'sending'
                ? '发送中'
                : status === 'success'
                  ? '发送成功'
                  : '发送失败'}
            >
              <Icon
                name={status === 'sending'
                  ? 'LoaderCircle'
                  : status === 'success'
                    ? 'Check'
                    : 'X'}
                size={14}
              />
            </span>
          {/if}
        </button>
      {/each}
      {#if activeTool}
        <div class={styles.tabBarActions}>
          {#if deliveryStates[activeTool.id]?.status === 'error' && onRetry}
            <button
              type="button"
              class={styles.retryButton}
              onclick={() => onRetry?.(activeTool.id)}
              aria-label={`重试 ${activeTool.name}`}
            >
              重试
            </button>
          {/if}
          <button
            class={styles.toolbarButton}
            onclick={() => navigate('goBack')}
            disabled={!canGoBack}
            aria-label={`后退 ${activeTool.name}`}
            title="后退"
          >
            <Icon name="ArrowLeft" size={16} />
          </button>
          <button
            class={styles.toolbarButton}
            onclick={() => navigate('goForward')}
            disabled={!canGoForward}
            aria-label={`前进 ${activeTool.name}`}
            title="前进"
          >
            <Icon name="ArrowRight" size={16} />
          </button>
          <button
            class={styles.toolbarButton}
            onclick={refresh}
            aria-label={`刷新 ${activeTool.name}`}
            title="刷新当前页面"
          >
            <Icon name="RefreshCw" size={16} />
          </button>
          <button
            class={`${styles.toolbarButton} ${styles.toolbarButtonDanger}`}
            onclick={clearCache}
            disabled={isClearingData}
            aria-label={`清理 ${activeTool.name} 缓存`}
            title="清理所有缓存数据"
          >
            <Icon name="Eraser" size={16} />
          </button>
        </div>
      {/if}
    </div>
    {#if activeTool && isToolIncognito(session, activeTool.id)}
      <div class={styles.incognitoBanner} role="status">
        <Icon name="EyeOff" size={14} />
        <span>
          您已进入无痕模式。Cookie、缓存与登录态不会写入磁盘，切换或关闭后将清除。
        </span>
      </div>
    {/if}
    <div class={styles.tabPanels}>
      {#each selectedTools as tool (tool.id)}
        {@const partition = getToolPartitionFromSettings(tool.id, session)}
        {@const incognito = isToolIncognito(session, tool.id)}
        <div
          id={`panel-${tool.id}`}
          role="tabpanel"
          aria-labelledby={`tab-${tool.id}`}
          class={`${styles.tabPane} ${tool.id === activeTabId ? styles.tabPaneActive : styles.tabPaneHidden}`}
          aria-hidden={tool.id !== activeTabId}
          inert={tool.id !== activeTabId}
        >
          <div
            class={styles.webviewContainer}
            aria-label={`${tool.name} 内容区域`}
          >
            {#key `${tool.id}-${proxyRevision}-${partition}`}
              <ElectronWebView
                src={tool.url}
                {partition}
                toolId={tool.id}
                label={`${tool.name} Webview`}
                {incognito}
                onElement={(element) => attach(tool, incognito, element)}
              />
            {/key}
          </div>
          {#if tool.id === activeTabId && deliveryStates[tool.id]?.status === 'error' && deliveryStates[tool.id].errorMessage}
            <div class={styles.errorMessage} role="alert">
              {deliveryStates[tool.id].errorMessage}
            </div>
          {/if}
        </div>
      {/each}
    </div>
  </div>
{/if}
