// src/components/ui/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements';
  import styles from './Input.module.css';
  const uid = $props.id();
  let {
    label,
    error,
    helperText,
    class: className = '',
    id = uid,
    ...props
  }: HTMLInputAttributes & {
    label?: string;
    error?: string;
    helperText?: string;
  } = $props();
</script>

<div class={styles.inputWrapper}>
  {#if label}<label for={id} class={styles.label}>{label}</label>{/if}
  <input
    {id}
    class={[styles.input, error && styles['input--error'], className]
      .filter(Boolean)
      .join(' ')}
    aria-invalid={!!error}
    aria-describedby={error
      ? `${id}-error`
      : helperText
        ? `${id}-helper`
        : undefined}
    {...props}
  />
  {#if error}<span id={`${id}-error`} class={styles.errorText} role="alert">
      {error}
    </span>{/if}
  {#if helperText && !error}<span id={`${id}-helper`} class={styles.helperText}>
      {helperText}
    </span>{/if}
</div>

// src/components/ui/Input.tsx
import { InputHTMLAttributes, forwardRef } from 'react';
import styles from './Input.module.css';

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
}

/**
 * Input 组件
 * 支持标签、错误提示和帮助文本
 */
export const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ label, error, helperText, className = '', id, ...props }, ref) => {
    const inputId = id || `input-${Math.random().toString(36).substr(2, 9)}`;
    const hasError = !!error;

    return (
      <div className={styles.inputWrapper}>
        {label && (
          <label htmlFor={inputId} className={styles.label}>
            {label}
          </label>
        )}
        <input
          ref={ref}
          id={inputId}
          className={[
            styles.input,
            hasError && styles['input--error'],
            className,
          ]
            .filter(Boolean)
            .join(' ')}
          aria-invalid={hasError}
          aria-describedby={
            error ? `${inputId}-error` : helperText ? `${inputId}-helper` : undefined
          }
          {...props}
        />
        {error && (
          <span id={`${inputId}-error`} className={styles.errorText} role="alert">
            {error}
          </span>
        )}
        {helperText && !error && (
          <span id={`${inputId}-helper`} className={styles.helperText}>
            {helperText}
          </span>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';

export default Input;
